#!/bin/bash
#
# run_now.sh - Execute the current test
#
# This file is regenerated by Claude Code each time a test needs to run.
# Just execute: ./run_now.sh
#
# Current test: RT_ram_mount_handle_tests (RAM Mount/Handle/Format Tests)
#

../tools/run_test.sh RT_ram_mount_handle_tests "$(dirname "$0")" -t 120
