#!/bin/bash
#
# run_now.sh - Execute the current test
#
# This file is regenerated by Claude Code each time a test needs to run.
# Just execute: ./run_now.sh
#
# Current test: RT_ram_read_write_tests (RAM Drive Read/Write Verification)
#

../tools/run_test.sh RT_ram_read_write_tests "$(dirname "$0")" -t 120
